<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="idoshoshani-lt" name="com.myTests.NativeTest" tests="2" failures="0" timestamp="26 Nov 2017 09:21:06 GMT" time="312.318" errors="2">
  <testcase name="testNativeLogin" time="156.509" classname="com.myTests.NativeTest">
    <error type="com.experitest.client.InternalException" message="Exception caught while executing elementSendText: Element was not identified: &#039;usernameTextField&#039; at zone default">
      <![CDATA[com.experitest.client.InternalException: Exception caught while executing elementSendText: Element was not identified: 'usernameTextField' at zone default
	at com.experitest.client.JavaClientInternals.executeInternally(JavaClientInternals.java:249)
	at com.experitest.client.Client.execute(Client.java:247)
	at com.experitest.client.ExecutionClient.execute(ExecutionClient.java:184)
	at com.experitest.client.Client.elementSendText(Client.java:807)
	at com.myTests.NativeTest.testNativeLogin(NativeTest.java:80)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- testNativeLogin -->
  <testcase name="OrderTest" time="155.809" classname="com.myTests.NativeTest">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.experitest.client.Client.hybridRunJavascript(Client.java:1376)
	at com.myTests.NativeTest.OrderTest(NativeTest.java:110)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- OrderTest -->
</testsuite> <!-- com.myTests.NativeTest -->
